2018-09-27 15:27:27 : demo_test_all{"created: "False""result" : "updated" }
2018-10-11 15:45:40 : demo_test_all : Traceback (most recent call last):
  File "create_dash.py", line 52, in main
    logStatus(id, response, log_file_location)
  File "create_dash.py", line 89, in logStatus
    ' : ' + dashboard_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:46:03 : demo_test_all : {u'status': 404, u'error': {u'index_uuid': u'gfWoDl66ThSyfbUnRDdYxw', u'index': u'.kibana-6', u'root_cause': [{u'index_uuid': u'gfWoDl66ThSyfbUnRDdYxw', u'index': u'.kibana-6', u'reason': u'type[dashboard] missing', u'type': u'type_missing_exception'}], u'caused_by': {u'reason': u'trying to auto create mapping, but dynamic mapping is disabled', u'type': u'illegal_state_exception'}, u'reason': u'type[dashboard] missing', u'type': u'type_missing_exception'}}
2018-10-11 15:47:10 : demo_test_all : Traceback (most recent call last):
  File "create_dash.py", line 49, in main
    response = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2018-10-11 16:01:07 : demo_test_all : Traceback (most recent call last):
  File "create_dash.py", line 49, in main
    response = requests.put(elk_url, json=payload).json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2018-10-11 16:02:01 : demo_test_all : Traceback (most recent call last):
  File "create_dash.py", line 49, in main
    response = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2018-10-11 16:04:37 : demo_test_all : Traceback (most recent call last):
  File "create_dash.py", line 50, in main
    response = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2018-10-11 16:05:15 : demo_test_all : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'dashboard:demo_test_all'}
2018-10-11 16:12:28 : demo_test_all : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'dashboard:demo_test_all'}
2018-10-11 16:21:06 : cassandra_time_metrics_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'dashboard:cassandra_time_metrics_blue'}
2019-01-17 12:14:09 : lagom_speeds_and_feeds_blue_DEMO : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'dashboard:lagom_speeds_and_feeds_blue_DEMO'}
2019-01-17 12:16:28 : lagom_speeds_and_feeds_blue_DEMO : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'dashboard:lagom_speeds_and_feeds_blue_DEMO'}
2019-01-17 12:28:48 : lagom_speeds_and_feeds_blue_DEMO : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 3, u'created': False, u'result': u'updated', u'_id': u'dashboard:lagom_speeds_and_feeds_blue_DEMO'}
2019-01-17 12:39:20 : lagom_speeds_and_feeds_blue_DEMO : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': False, u'result': u'updated', u'_id': u'dashboard:lagom_speeds_and_feeds_blue_DEMO'}
