2018-09-27 15:22:10 : storeserv_lagom_blue_table_of_contents{"created: "False""result" : "updated" }
2018-09-27 15:22:11 : storeserv_lagom_blue_file_write_to_cassandra_time{"created: "False""result" : "updated" }
2018-09-27 15:22:13 : storeserv_lagom_blue_file_read_from_cassandra_time{"created: "False""result" : "updated" }
2018-09-27 15:22:14 : storeserv_lagom_blue_cassandra_processed_data_read_times{"created: "False""result" : "updated" }
2018-09-27 15:22:15 : storeserv_lagom_blue_cassandra_processed_data_write_times{"created: "False""result" : "updated" }
2018-09-27 15:22:18 : systemfilesactor_state_write_to_cassandra_time_blue{"created: "False""result" : "updated" }
2018-09-27 15:22:19 : systemfilesactor_state_read_from_cassandra_time_blue{"created: "False""result" : "updated" }
2018-09-27 15:22:21 : storeserv_lagom_cassandra_read_times_blue{"created: "False""result" : "updated" }
2018-09-27 15:22:38 : storeserv_lagom_blue_table_of_contents{"created: "False""result" : "updated" }
2018-09-27 15:22:39 : storeserv_lagom_blue_file_write_to_cassandra_time{"created: "False""result" : "updated" }
2018-09-27 15:22:41 : storeserv_lagom_blue_file_read_from_cassandra_time{"created: "False""result" : "updated" }
2018-09-27 15:22:42 : storeserv_lagom_blue_cassandra_processed_data_read_times{"created: "False""result" : "updated" }
2018-09-27 15:22:44 : storeserv_lagom_blue_cassandra_processed_data_write_times{"created: "False""result" : "updated" }
2018-09-27 15:22:45 : systemfilesactor_state_write_to_cassandra_time_blue{"created: "False""result" : "updated" }
2018-09-27 15:22:46 : systemfilesactor_state_read_from_cassandra_time_blue{"created: "False""result" : "updated" }
2018-09-27 15:22:48 : storeserv_lagom_cassandra_read_times_blue{"created: "False""result" : "updated" }
2018-09-27 18:41:11 : storeserv_lagom_blue_table_of_contents{"created: "False""result" : "updated" }
2018-09-27 18:41:13 : storeserv_lagom_blue_file_write_to_cassandra_time{"created: "False""result" : "updated" }
2018-09-27 18:41:14 : storeserv_lagom_blue_file_read_from_cassandra_time{"created: "False""result" : "updated" }
2018-09-27 18:41:16 : storeserv_lagom_blue_cassandra_processed_data_read_times{"created: "False""result" : "updated" }
2018-09-27 18:41:17 : storeserv_lagom_blue_cassandra_processed_data_write_times{"created: "False""result" : "updated" }
2018-09-27 18:41:19 : systemfilesactor_state_write_to_cassandra_time_blue{"created: "False""result" : "updated" }
2018-09-27 18:41:20 : systemfilesactor_state_read_from_cassandra_time_blue{"created: "False""result" : "updated" }
2018-09-27 18:41:21 : storeserv_lagom_cassandra_read_times_blue{"created: "False""result" : "updated" }
2018-10-03 12:00:48 : storeserv_lagom_blue_table_of_contents : Traceback (most recent call last):
  File "create_visual.py", line 50, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='elk-saturn.storefrontremote.com', port=80): Max retries exceeded with url: /.kibana/visualization/storeserv_lagom_blue_table_of_contents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1fe7a94590>: Failed to establish a new connection: [Errno 110] Connection timed out',))

2018-10-03 12:02:42 : storeserv_lagom_blue_file_write_to_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 50, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-03 12:02:43 : storeserv_lagom_blue_file_read_from_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 50, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-03 12:02:44 : storeserv_lagom_blue_cassandra_processed_data_read_times : Traceback (most recent call last):
  File "create_visual.py", line 50, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-03 12:02:45 : storeserv_lagom_blue_cassandra_processed_data_write_times : Traceback (most recent call last):
  File "create_visual.py", line 50, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-03 12:02:45 : systemfilesactor_state_write_to_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 50, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-03 12:02:46 : systemfilesactor_state_read_from_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 50, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-03 12:02:46 : storeserv_lagom_cassandra_read_times_blue : Traceback (most recent call last):
  File "create_visual.py", line 50, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:48:10 : storeserv_lagom_blue_table_of_contents : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:48:11 : storeserv_lagom_blue_file_write_to_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:48:12 : storeserv_lagom_blue_file_read_from_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:48:12 : storeserv_lagom_blue_cassandra_processed_data_read_times : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:48:13 : storeserv_lagom_blue_cassandra_processed_data_write_times : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:48:13 : systemfilesactor_state_write_to_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:48:13 : systemfilesactor_state_read_from_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:48:14 : storeserv_lagom_cassandra_read_times_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:49:39 : storeserv_lagom_blue_table_of_contents : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:49:43 : storeserv_lagom_blue_file_write_to_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:49:45 : storeserv_lagom_blue_file_read_from_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:49:46 : storeserv_lagom_blue_cassandra_processed_data_read_times : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:49:48 : storeserv_lagom_blue_cassandra_processed_data_write_times : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:49:49 : systemfilesactor_state_write_to_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:49:50 : systemfilesactor_state_read_from_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:49:51 : storeserv_lagom_cassandra_read_times_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 11:57:22 : storeserv_lagom_blue_table_of_contents : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='elk-saturn.storefrontremote.com', port=80): Max retries exceeded with url: /.kibana/visualization/storeserv_lagom_blue_table_of_contents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1014425510>: Failed to establish a new connection: [Errno 110] Connection timed out',))

2018-10-04 12:01:44 : storeserv_lagom_blue_file_write_to_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='elk-saturn.storefrontremote.com', port=80): Max retries exceeded with url: /.kibana/visualization/storeserv_lagom_blue_file_write_to_cassandra_time (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1013b5b710>: Failed to establish a new connection: [Errno 110] Connection timed out',))

2018-10-04 12:06:06 : storeserv_lagom_blue_file_read_from_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='elk-saturn.storefrontremote.com', port=80): Max retries exceeded with url: /.kibana/visualization/storeserv_lagom_blue_file_read_from_cassandra_time (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1013b5b550>: Failed to establish a new connection: [Errno 110] Connection timed out',))

2018-10-04 12:10:28 : storeserv_lagom_blue_cassandra_processed_data_read_times : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='elk-saturn.storefrontremote.com', port=80): Max retries exceeded with url: /.kibana/visualization/storeserv_lagom_blue_cassandra_processed_data_read_times (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1013b5b6d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

2018-10-04 12:13:57 : storeserv_lagom_blue_cassandra_processed_data_write_times : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 12:13:59 : systemfilesactor_state_write_to_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 12:14:00 : systemfilesactor_state_read_from_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-04 12:14:01 : storeserv_lagom_cassandra_read_times_blue : Traceback (most recent call last):
  File "create_visual.py", line 53, in main
    request_result = json.loads(requests.put(elk_url, json=payload).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

2018-10-11 15:06:05 : storeserv_lagom_blue_table_of_contents : Traceback (most recent call last):
  File "create_visual.py", line 52, in main
    payload = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 2 (char 28)

2018-10-11 15:06:05 : storeserv_lagom_blue_file_write_to_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 52, in main
    payload = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 2 (char 28)

2018-10-11 15:06:05 : storeserv_lagom_blue_file_read_from_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 52, in main
    payload = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 2 (char 28)

2018-10-11 15:06:05 : storeserv_lagom_blue_cassandra_processed_data_read_times : Traceback (most recent call last):
  File "create_visual.py", line 52, in main
    payload = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 2 (char 28)

2018-10-11 15:06:05 : storeserv_lagom_blue_cassandra_processed_data_write_times : Traceback (most recent call last):
  File "create_visual.py", line 52, in main
    payload = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 2 (char 28)

2018-10-11 15:06:05 : systemfilesactor_state_write_to_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 52, in main
    payload = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 2 (char 28)

2018-10-11 15:06:05 : systemfilesactor_state_read_from_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 52, in main
    payload = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 2 (char 28)

2018-10-11 15:06:05 : storeserv_lagom_cassandra_read_times_blue : Traceback (most recent call last):
  File "create_visual.py", line 52, in main
    payload = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 2 (char 28)

2018-10-11 15:07:38 : storeserv_lagom_blue_table_of_contents : Traceback (most recent call last):
  File "create_visual.py", line 56, in main
    logStatus(id, request_result, log_file_location)
  File "create_visual.py", line 80, in logStatus
    ' : ' + visual_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:07:39 : storeserv_lagom_blue_file_write_to_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 56, in main
    logStatus(id, request_result, log_file_location)
  File "create_visual.py", line 80, in logStatus
    ' : ' + visual_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:07:40 : storeserv_lagom_blue_file_read_from_cassandra_time : Traceback (most recent call last):
  File "create_visual.py", line 56, in main
    logStatus(id, request_result, log_file_location)
  File "create_visual.py", line 80, in logStatus
    ' : ' + visual_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:07:41 : storeserv_lagom_blue_cassandra_processed_data_read_times : Traceback (most recent call last):
  File "create_visual.py", line 56, in main
    logStatus(id, request_result, log_file_location)
  File "create_visual.py", line 80, in logStatus
    ' : ' + visual_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:07:43 : storeserv_lagom_blue_cassandra_processed_data_write_times : Traceback (most recent call last):
  File "create_visual.py", line 56, in main
    logStatus(id, request_result, log_file_location)
  File "create_visual.py", line 80, in logStatus
    ' : ' + visual_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:07:44 : systemfilesactor_state_write_to_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 56, in main
    logStatus(id, request_result, log_file_location)
  File "create_visual.py", line 80, in logStatus
    ' : ' + visual_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:07:45 : systemfilesactor_state_read_from_cassandra_time_blue : Traceback (most recent call last):
  File "create_visual.py", line 56, in main
    logStatus(id, request_result, log_file_location)
  File "create_visual.py", line 80, in logStatus
    ' : ' + visual_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:07:46 : storeserv_lagom_cassandra_read_times_blue : Traceback (most recent call last):
  File "create_visual.py", line 56, in main
    logStatus(id, request_result, log_file_location)
  File "create_visual.py", line 80, in logStatus
    ' : ' + visual_id + ' : ' + response
TypeError: cannot concatenate 'str' and 'dict' objects

2018-10-11 15:17:26 : storeserv_lagom_blue_table_of_contents : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'storeserv_lagom_blue_table_of_contents'}
2018-10-11 15:17:27 : storeserv_lagom_blue_file_write_to_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'storeserv_lagom_blue_file_write_to_cassandra_time'}
2018-10-11 15:17:28 : storeserv_lagom_blue_file_read_from_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'storeserv_lagom_blue_file_read_from_cassandra_time'}
2018-10-11 15:17:29 : storeserv_lagom_blue_cassandra_processed_data_read_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'storeserv_lagom_blue_cassandra_processed_data_read_times'}
2018-10-11 15:17:31 : storeserv_lagom_blue_cassandra_processed_data_write_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'storeserv_lagom_blue_cassandra_processed_data_write_times'}
2018-10-11 15:17:32 : systemfilesactor_state_write_to_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'systemfilesactor_state_write_to_cassandra_time_blue'}
2018-10-11 15:17:33 : systemfilesactor_state_read_from_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'systemfilesactor_state_read_from_cassandra_time_blue'}
2018-10-11 15:17:34 : storeserv_lagom_cassandra_read_times_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 2, u'created': False, u'result': u'updated', u'_id': u'storeserv_lagom_cassandra_read_times_blue'}
2018-10-11 15:25:29 : storeserv_lagom_blue_table_of_contents : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'storeserv_lagom_blue_table_of_contents'}
2018-10-11 15:25:30 : storeserv_lagom_blue_file_write_to_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'storeserv_lagom_blue_file_write_to_cassandra_time'}
2018-10-11 15:25:32 : storeserv_lagom_blue_file_read_from_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'storeserv_lagom_blue_file_read_from_cassandra_time'}
2018-10-11 15:25:33 : storeserv_lagom_blue_cassandra_processed_data_read_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'storeserv_lagom_blue_cassandra_processed_data_read_times'}
2018-10-11 15:25:34 : storeserv_lagom_blue_cassandra_processed_data_write_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'storeserv_lagom_blue_cassandra_processed_data_write_times'}
2018-10-11 15:25:35 : systemfilesactor_state_write_to_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'systemfilesactor_state_write_to_cassandra_time_blue'}
2018-10-11 15:25:36 : systemfilesactor_state_read_from_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'systemfilesactor_state_read_from_cassandra_time_blue'}
2018-10-11 15:25:37 : storeserv_lagom_cassandra_read_times_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'storeserv_lagom_cassandra_read_times_blue'}
2018-10-11 15:37:35 : visualization:storeserv_lagom_blue_table_of_contents : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_table_of_contents'}
2018-10-11 15:37:36 : visualization:storeserv_lagom_blue_file_write_to_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_file_write_to_cassandra_time'}
2018-10-11 15:37:37 : visualization:storeserv_lagom_blue_file_read_from_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_file_read_from_cassandra_time'}
2018-10-11 15:37:38 : visualization:storeserv_lagom_blue_cassandra_processed_data_read_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_cassandra_processed_data_read_times'}
2018-10-11 15:37:40 : visualization:storeserv_lagom_blue_cassandra_processed_data_write_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_cassandra_processed_data_write_times'}
2018-10-11 15:37:41 : visualization:systemfilesactor_state_write_to_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:systemfilesactor_state_write_to_cassandra_time_blue'}
2018-10-11 15:37:42 : visualization:systemfilesactor_state_read_from_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:systemfilesactor_state_read_from_cassandra_time_blue'}
2018-10-11 15:37:43 : visualization:storeserv_lagom_cassandra_read_times_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_cassandra_read_times_blue'}
2018-10-11 16:20:42 : visualization:storeserv_lagom_blue_table_of_contents : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 4, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_table_of_contents'}
2018-10-11 16:20:44 : visualization:storeserv_lagom_blue_file_write_to_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 3, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_file_write_to_cassandra_time'}
2018-10-11 16:20:45 : visualization:storeserv_lagom_blue_file_read_from_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 3, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_file_read_from_cassandra_time'}
2018-10-11 16:20:46 : visualization:storeserv_lagom_blue_cassandra_processed_data_read_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 3, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_cassandra_processed_data_read_times'}
2018-10-11 16:20:47 : visualization:storeserv_lagom_blue_cassandra_processed_data_write_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 3, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_cassandra_processed_data_write_times'}
2018-10-11 16:20:48 : visualization:systemfilesactor_state_write_to_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 3, u'created': True, u'result': u'created', u'_id': u'visualization:systemfilesactor_state_write_to_cassandra_time_blue'}
2018-10-11 16:20:53 : visualization:systemfilesactor_state_read_from_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 3, u'created': True, u'result': u'created', u'_id': u'visualization:systemfilesactor_state_read_from_cassandra_time_blue'}
2018-10-11 16:20:54 : visualization:storeserv_lagom_cassandra_read_times_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 3, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_cassandra_read_times_blue'}
2018-10-11 17:39:28 : visualization:storeserv_lagom_blue_table_of_contents : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 6, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_table_of_contents'}
2018-10-11 17:39:30 : visualization:storeserv_lagom_blue_file_write_to_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 5, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_file_write_to_cassandra_time'}
2018-10-11 17:39:31 : visualization:storeserv_lagom_blue_file_read_from_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 5, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_file_read_from_cassandra_time'}
2018-10-11 17:39:32 : visualization:storeserv_lagom_blue_cassandra_processed_data_read_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 5, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_cassandra_processed_data_read_times'}
2018-10-11 17:39:34 : visualization:storeserv_lagom_blue_cassandra_processed_data_write_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 5, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_cassandra_processed_data_write_times'}
2018-10-11 17:39:35 : visualization:systemfilesactor_state_write_to_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 5, u'created': True, u'result': u'created', u'_id': u'visualization:systemfilesactor_state_write_to_cassandra_time_blue'}
2018-10-11 17:39:37 : visualization:systemfilesactor_state_read_from_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 5, u'created': True, u'result': u'created', u'_id': u'visualization:systemfilesactor_state_read_from_cassandra_time_blue'}
2018-10-11 17:39:38 : visualization:storeserv_lagom_cassandra_read_times_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 5, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_cassandra_read_times_blue'}
2018-10-11 18:51:10 : visualization:storeserv_lagom_blue_table_of_contents : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_table_of_contents'}
2018-10-11 18:51:12 : visualization:storeserv_lagom_blue_file_write_to_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_file_write_to_cassandra_time'}
2018-10-11 18:51:13 : visualization:storeserv_lagom_blue_file_read_from_cassandra_time : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_file_read_from_cassandra_time'}
2018-10-11 18:51:14 : visualization:storeserv_lagom_blue_cassandra_processed_data_read_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_cassandra_processed_data_read_times'}
2018-10-11 18:51:16 : visualization:storeserv_lagom_blue_cassandra_processed_data_write_times : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_blue_cassandra_processed_data_write_times'}
2018-10-11 18:51:17 : visualization:systemfilesactor_state_write_to_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:systemfilesactor_state_write_to_cassandra_time_blue'}
2018-10-11 18:51:19 : visualization:systemfilesactor_state_read_from_cassandra_time_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:systemfilesactor_state_read_from_cassandra_time_blue'}
2018-10-11 18:51:20 : visualization:storeserv_lagom_cassandra_read_times_blue : {u'_type': u'doc', u'_shards': {u'successful': 2, u'failed': 0, u'total': 2}, u'_index': u'.kibana-6', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'visualization:storeserv_lagom_cassandra_read_times_blue'}
